STUDENT_ORGS = [
    {
        "id": "1",
        "name": "Transfer Student Association",
        "abbreviation": "TSA",
        "description": "The official voice of transfer students at UCSD. We advocate for transfer resources, host social events, and build community for students navigating the transfer experience.",
        "website": "https://tsa.ucsd.edu",
        "instagram": "@ucsd_tsa",
    },
    {
        "id": "2",
        "name": "ACM at UC San Diego",
        "abbreviation": "ACM",
        "description": "The largest computer science organization at UCSD. We run workshops, hackathons, and industry panels to help students grow technically and professionally.",
        "website": "https://acmucsd.com",
        "instagram": "@acmucsd",
    },
    {
        "id": "3",
        "name": "Triton Gaming",
        "abbreviation": "TG",
        "description": "UCSD's premier gaming community. We host weekly gaming nights, esports tournaments, and casual hangout sessions for gamers of all types.",
        "website": None,
        "instagram": "@tritongaming_ucsd",
    },
    {
        "id": "4",
        "name": "Society of Women Engineers",
        "abbreviation": "SWE",
        "description": "Empowering women and allies in engineering. We connect students with mentors, host professional development workshops, and advocate for inclusion in tech.",
        "website": "https://swe.ucsd.edu",
        "instagram": "@swe_ucsd",
    },
    {
        "id": "5",
        "name": "UCSD Salsa Club",
        "abbreviation": "Salsa",
        "description": "Learn salsa, bachata, and other Latin dances in a welcoming environment. No partner or experience required. Free lessons every week.",
        "website": None,
        "instagram": "@ucsd_salsa",
    },
    {
        "id": "6",
        "name": "Triton Consulting Group",
        "abbreviation": "TCG",
        "description": "A student-run consulting organization providing pro-bono consulting services to local nonprofits and startups while developing business skills.",
        "website": "https://tcg.ucsd.edu",
        "instagram": "@tcg_ucsd",
    },
    {
        "id": "7",
        "name": "International Student Association",
        "abbreviation": "ISA",
        "description": "Celebrating the rich diversity of UCSD's international community. We host cultural events, provide resources, and build bridges across nationalities.",
        "website": None,
        "instagram": "@isa_ucsd",
    },
    {
        "id": "8",
        "name": "Design Co",
        "abbreviation": "DCo",
        "description": "UCSD's premier design organization, connecting students passionate about UX, product design, and visual communication through workshops and speaker events.",
        "website": "https://designco.ucsd.edu",
        "instagram": "@designco_ucsd",
    },
]
